sudo: required
dist: trusty
language: node_js
node_js:
- 6.9.2
before_install:
- npm i -g npm@3.10.9
install: npm install
deploy:
  api-key:
    secure: $HEROKU_API_KEY
  app: ongbook
  provider: heroku
